name: MansonCo
favicon: null
layout_spectrum: 0.71387
typography_spectrum: 0.8349048781674355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc6c5e'
    - '#6c6c6c'
    - '#000000'
    - '#ff0000'
    - '#bf4040'
  brandStrength: 0.375
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
