name: MansonCo
favicon: null
layout_spectrum: 0.49067
typography_spectrum: 0.87704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff5f4f'
    - '#616161'
    - '#000000'
    - '#ff0000'
    - '#ff8000'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
