name: MansonCo
favicon: null
layout_spectrum: 0.5263911420479417
typography_spectrum: 0.8349048781674355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.27268598950468004
  lightness: 0.8150370377115905
  saturation: 0.17328436858952045
  rhythmicContrast: 0.550932474900037
purpose: []
